# Generated by Django 2.0.7 on 2018-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180728_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='/teacher/2018/07/to.jpg', upload_to='teacher/%Y/%m', verbose_name='讲师头像'),
        ),
    ]
