# Generated by Django 2.0.7 on 2018-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180806_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(blank=True, default='teacher/2018/07/to.jpg', upload_to='teacher/%Y/%m', verbose_name='讲师头像'),
        ),
    ]
