# Generated by Django 2.0.7 on 2018-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180806_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_courses',
            field=models.IntegerField(default=0, verbose_name='教师课程数'),
        ),
    ]
