# Generated by Django 2.0.7 on 2018-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180717_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构'), (3, '教师')], default=1, verbose_name='收藏类型'),
        ),
    ]
