# Generated by Django 2.0.7 on 2018-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180717_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wang',
            name='image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/%Y/%m'),
        ),
    ]
