# Generated by Django 2.0.7 on 2018-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180813_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wang',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/%Y/%m'),
        ),
    ]
