# Generated by Django 2.0.7 on 2018-08-21 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180819_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wang',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='生日'),
        ),
    ]
