# Generated by Django 2.0.7 on 2018-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180821_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wang',
            name='image',
            field=models.ImageField(blank=True, default='images/to.png', null=True, upload_to='images/%Y/%m'),
        ),
    ]
